---Problem - 1
GO

CREATE DATABASE [CigarShop]
GO

USE [CigarShop]
GO

CREATE TABLE [Sizes](
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[Length] INT NOT NULL,
	CHECK (([Length]) BETWEEN 10 AND 25),
	[RingRange] DECIMAL(18,2) NOT NULL,
	CHECK (([RingRange]) BETWEEN 1.5 AND 7.5)
)
GO

CREATE TABLE [Tastes](
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[TasteType] VARCHAR(20) NOT NULL,
	[TasteStrength] VARCHAR(15)NOT NULL,
	[ImageURL] NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE [Brands](
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[BrandName] VARCHAR(30) UNIQUE NOT NULL,
	[BrandDescription] VARCHAR(MAX)
)
GO

CREATE TABLE [Cigars](
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[CigarName] VARCHAR(80) NOT NULL,
	[BrandId] INT FOREIGN KEY REFERENCES [Brands]([Id]) NOT NULL,
	[TastId] INT FOREIGN KEY REFERENCES [Tastes]([Id]) NOT NULL,
	[SizeId] INT NOT NULL FOREIGN KEY REFERENCES [Sizes]([Id]), --ON UPDATE  NO ACTION  ON DELETE  CASCADE ,
	--PRIMARY KEY CLUSTERED ( [Id], [SizeId]),
	[PriceForSingleCigar] DECIMAL(19,4) NOT NULL,
	[ImageURL] NVARCHAR(100) NOT NULL

)
GO

CREATE TABLE [Addresses](
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[Town] VARCHAR(30) NOT NULL,
	[Country] NVARCHAR(30) NOT NULL,
	[Streat] NVARCHAR(100) NOT NULL,
	[ZIP] VARCHAR(20) NOT NULL,
)
GO

CREATE TABLE [Clients](
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[FirstName] NVARCHAR(30) NOT NULL,
	[LastName] NVARCHAR(30) NOT NULL,
	[Email] NVARCHAR(30) NOT NULL,
	[AddressId] INT FOREIGN KEY REFERENCES [Addresses]([Id]) NOT NULL
)
GO

CREATE TABLE [ClientsCigars](
	[ClientId] INT FOREIGN KEY REFERENCES [Clients]([Id]) NOT NULL,
	[CigarId] INT FOREIGN KEY REFERENCES [Cigars]([Id]) NOT NULL,
	CONSTRAINT PK_ClientIdCigarId PRIMARY KEY ([ClientId], [CigarId]),
)
GO
